[package]
name = "tracing-tracy"
version = "0.1.2"
authors = ["Simonas Kazlauskas <tracing-tracy@kazlauskas.me>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "../README.mkd"
repository = "https://github.com/nagisa/rust_tracy_client"
homepage = "https://github.com/nagisa/rust_tracy_client"
documentation = "https://docs.rs/tracing-tracy"
description = """
Inspect tracing-enabled Rust applications with Tracy
"""

[dependencies]
tracing-core = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.2", default-features = false, features = ["registry"] }
tracy-client = { path = "../tracy-client", default-features = false }

[dev-dependencies]
tracing = { version = "0.1", default-features = false, features = ["std"] }
tokio = { version = "0.2", features = ["full"] }
tracing-attributes =  { version = "0.1"}
tracing-futures = { version = "0.2" }
futures = "0.3"

[features]
default = [ "enable" ]
enable = [ "tracy-client/enable" ]
delayed-init = [ "tracy-client/delayed-init" ]
lowres-timer = [ "tracy-client/lowres-timer" ]
noexit = [ "tracy-client/noexit" ]
