[package]
name = "tracy-client"
version = "0.9.0"
authors = ["Simonas Kazlauskas <tracy-client@kazlauskas.me>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "../README.mkd"
repository = "https://github.com/nagisa/rust_tracy_client"
homepage = "https://github.com/nagisa/rust_tracy_client"
documentation = "https://docs.rs/tracy-client"
description = """
High level bindings to the client libraries for the Tracy profiler
"""

[dependencies]
tracy-client-sys = { path = "../tracy-client-sys", version = "0.10.0", default-features = false }

[features]
default = [ "enable" ]
enable = [ "tracy-client-sys/enable" ]
delayed-init = [ "tracy-client-sys/delayed-init" ]
lowres-timer = [ "tracy-client-sys/lowres-timer" ]
noexit = [ "tracy-client-sys/noexit" ]
use-external-tracy-library = [ "tracy-client-sys/use-external-tracy-library" ]
